### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by cigrainger** [lebrunel/ollama-ex#3]
Hey! Nice library :). Is there a way to configure the Req requests here to avoid timeouts?

**Comment by aaronrussell** [comment]
Thanks!

For now you can create the Req request manually and pass that to `Ollama.init/1`

```elixir
client =
  Req.new(base_url: "http://localhost:11434/api", ...other options...)
  |> Ollama.init()
```

There needs to be 1) better defaults, and 2) a more ergonomic way of tweaking opts like this. I'll think on this.

**Comment by cigrainger** [comment]
Oh nice! That's helpful to know. Thanks :)

**Comment by aaronrussell** [comment]
@cigrainger just released a small update. Receive timeout now defaults to 60s (instead of 15s), and `init/1` now accepts keyword options that are passed through to `Req.new/1`.

So you can now do `Ollama.init(receive_timeout: :infinity)` if you want to kill timeouts.
