### ISSUE TITLE
Implementing `/embed` endpoint (not `/embedding` )

### ISSUE THREAD

**Issue by tubedude** [lebrunel/ollama-ex#7]
Hey. 

I noticed the [documentation for the Ollama API](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings) has an endpoint that accepts as `input` a single string or a list of string.
Do you think it would be possible to implement it? As it works for both generating an embedding for a query and to store a list of documents?
I've actually [gave a try](https://github.com/tubedude/ollama-ex), but I'm having trouble testing it.

Thank you,

**Comment by aaronrussell** [comment]
I think that's a new feature as of yesterday! I haven't got round to it yet but will do over the weekend.

If you're satisfied your implementation works, just without tests, then do a PR and I'll add a test myself (the mock server testing code is a bit of a mess).

**Comment by nyo16** [comment]
@lebrunel I open a draft [PR ](https://github.com/lebrunel/ollama-ex/pull/8) with the functionality but not tests. Let me know if this is ok.

**Comment by aaronrussell** [comment]
Version `0.7.1` is out supporting the /embed endpoint.
